// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ddc
NumericVector ddc(NumericVector x, double mean, double sd, NumericVector phi);
RcppExport SEXP _davidRian_ddc(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(ddc(x, mean, sd, phi));
    return rcpp_result_gen;
END_RCPP
}
// rdc
NumericVector rdc(int n, double mean, double sd, NumericVector phi);
RcppExport SEXP _davidRian_rdc(SEXP nSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(rdc(n, mean, sd, phi));
    return rcpp_result_gen;
END_RCPP
}
// dcGrad
NumericVector dcGrad(NumericVector x, NumericVector phi);
RcppExport SEXP _davidRian_dcGrad(SEXP xSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(dcGrad(x, phi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_davidRian_ddc", (DL_FUNC) &_davidRian_ddc, 4},
    {"_davidRian_rdc", (DL_FUNC) &_davidRian_rdc, 4},
    {"_davidRian_dcGrad", (DL_FUNC) &_davidRian_dcGrad, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_davidRian(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
