# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density function for Davidian curves
#'
#' Returns the density for a vector of x.
#'
#' @param x An integer vector
ddc <- function(x, k, mean, sd, phi) {
    .Call(`_davidRian_ddc`, x, k, mean, sd, phi)
}

#' Sampling from a given Davidian curves
#'
#' Samples n realizations from the specified Davidian Curve.
#'
#' @param x An integer vector
rdc <- function(n, k, mean, sd, phi) {
    .Call(`_davidRian_rdc`, n, k, mean, sd, phi)
}

dcGrad_ <- function(x, k, c, phi) {
    .Call(`_davidRian_dcGrad_`, x, k, c, phi)
}

