# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density function for Davidian curves
#'
#' Returns the density for a vector of x.
#'
#' @param x An integer vector
#' @name dcdens
dcdensC <- function(x, k, mean, sd, phi) {
    .Call(`_davidRian_dcdensC`, x, k, mean, sd, phi)
}

dcGrad_ <- function(x, k, c, phi) {
    .Call(`_davidRian_dcGrad_`, x, k, c, phi)
}

rdc <- function(n, k, mean, sd, phi) {
    .Call(`_davidRian_rdc`, n, k, mean, sd, phi)
}

